<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
   
    <xacro:macro name="cylinder_link" params="name material radius length">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 ${length / 2.0}" rpy="0 0 0" />
                <material name="${material}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <origin xyz="0 0 ${length / 2.0}" rpy="0 0 0" />
            </collision>
        <xacro:cylinder_inertia m="0.3" r="${radius}" h="${length}"
                        o_xyz="0 0 ${length / 2.0}" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:cylinder_link name="arm_base_link" material="yellow" radius="0.09" length="0.02" />
    <xacro:cylinder_link name="vertical_prismatic_link1" material="orange" radius="0.07" length="0.2" />
    <xacro:cylinder_link name="vertical_prismatic_link2" material="yellow" radius="0.06" length="0.2" />
    <xacro:cylinder_link name="vertical_prismatic_link3" material="orange" radius="0.05" length="0.2" />

    <xacro:cylinder_link name="horizontal_prismatic_link1" material="orange" radius="0.04" length="0.16" />
    <xacro:cylinder_link name="horizontal_prismatic_link2" material="yellow" radius="0.03" length="0.16" />
    <xacro:cylinder_link name="horizontal_prismatic_link3" material="orange" radius="0.02" length="0.16" />

    <link name="gripper_pitch_link">
        <visual>
            <geometry>
                <cylinder radius="0.005" length="0.038" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.005" length="0.038"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        </collision>
    <xacro:cylinder_inertia m="0.3" r="0.005" h="0.038"
                    o_xyz="0 0 0" o_rpy="${pi/2} 0 0" />
    </link>

    <joint name="arm_base_prismatic1_joint" type="fixed">
        <parent link="arm_base_link" />
        <child link="vertical_prismatic_link1" />
        <origin xyz="0 0 0.02" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="vertical_prismatic1_2_joint" type="prismatic">
        <parent link="vertical_prismatic_link1" />
        <child link="vertical_prismatic_link2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="0.16" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>


    <joint name="vertical_prismatic2_3_joint" type="prismatic">
        <parent link="vertical_prismatic_link2" />
        <child link="vertical_prismatic_link3" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <mimic joint="vertical_prismatic1_2_joint" multiplier="1" offset="0"/>
        <limit lower="0" upper="0.16" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="horizontal_vertical_prismatic_joint" type="fixed">
        <parent link="vertical_prismatic_link3" />
        <child link="horizontal_prismatic_link1" />
        <origin xyz="-0.03 0 ${0.2 - 0.05}" rpy="0 ${pi/2} 0" />
    </joint>

    <joint name="horizontal_prismatic1_2_joint" type="prismatic">
        <parent link="horizontal_prismatic_link1" />
        <child link="horizontal_prismatic_link2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="0.16" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="horizontal_prismatic2_3_joint" type="prismatic">
        <parent link="horizontal_prismatic_link2" />
        <child link="horizontal_prismatic_link3" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <mimic joint="horizontal_prismatic1_2_joint" multiplier="1" offset="0"/>
        <limit lower="0" upper="0.16" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="horizontal_prismatic3_gripper_pitch_joint" type="revolute">
        <parent link="horizontal_prismatic_link3" />
        <child link="gripper_pitch_link" />
        <origin xyz="0 0 0.16" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>


</robot>