<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Body Variables -->
    <xacro:property name="base_length" value="0.65" />
    <xacro:property name="base_width" value="0.425" />
    <xacro:property name="base_height" value="0.205" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="caster_radius" value="${wheel_radius / 2.0}" />
  

    <!-- Link Definitions  -->
    <link name="base_footprint" />
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                        o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}"
                        o_xyz="0 0 0" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="back_right" />
    <xacro:wheel_link prefix="back_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" />

    <!-- Joint Definitions -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    
    <joint name="base_back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${-base_length / 3.0} ${-(base_width - wheel_length - 0.02) / 2.0} 0" rpy="-${pi / 2.0} 0 0"/>
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="${-base_length / 3.0} ${(base_width - wheel_length - 0.02) / 2.0} 0" rpy="-${pi / 2.0} 0 0"/>
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 3.0} ${-(base_width - wheel_length - 0.02) / 2.0} 0" rpy="-${pi / 2.0} 0 0"/>
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 3.0} ${(base_width - wheel_length - 0.02) / 2.0} 0" rpy="-${pi / 2.0} 0 0"/>
        <axis xyz="0 0 1" />
    </joint>

</robot>