<?xml version="1.0"?>
<robot name="libot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 'common_properties' should come first so other files have access to it -->
    <xacro:include filename="common_properties.xacro" /> 
    <xacro:include filename="libot_base.xacro" />
    <xacro:include filename="libot_base_gazebo.xacro" />
    <xacro:include filename="camera.xacro" />
    <xacro:include filename="standalone_arm.urdf.xacro" />

    <joint name="libot_arm_base_joint" type="continuous">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 3.5} 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

</robot>